
"""
This program will draw a comic with 2 bears (Milk and Mocha) looking out their
windows to see the starry night
"""

from turtle import*

speed(0)

# creating the  square panels
penup()
backward(370)
pendown()

def draw_panel():
     for i in range(4):
          forward(350)
          left(90)

fillcolor("lightslategrey")
begin_fill()
draw_panel()
end_fill()
penup()
forward(360)
pendown()
begin_fill()
draw_panel()
end_fill()
penup()
left(270)
forward(10)
pendown()
fillcolor("midnightblue")
begin_fill()
draw_panel()
end_fill()
penup()
right(90)
forward(10)
pendown()
begin_fill()
draw_panel()
end_fill()



# positioning mouse to first panel
penup()
forward(350)
right(90)
forward(10)
right(90)
forward(710)
right(90)
forward(10)
right(90)

# drawing first panel window frame
pensize(2)
penup()
setposition(-180, 180)

length=235

def starting_position():
     penup()
     left(270)
     forward(length/2)
     right(270)
     backward(length/2)

def outerframe(length):
  starting_position()
  pendown()
  for i in range(4):
       forward(length)
       left(90)
  penup()


def innerframe(length):
  starting_position()
  pendown()
  fillcolor("midnightblue")
  begin_fill()
  for i in range(4):
       forward(length)
       left(90)
  end_fill()

fillcolor("darkgrey")
begin_fill()
outerframe(length)
forward(150)
end_fill()
length= length-20
setposition(-180, 180)
innerframe(length)

# drawing first panel left open window
fillcolor("darkgrey")
begin_fill()
forward(215)
right(20)
forward(45)
left(110)
forward(230)
left(90)
forward(41)
left(90)
forward(215)
end_fill()

fillcolor("lightgrey")
begin_fill()
left(70)
forward(45)
left(20)
forward(10)
left(90)
forward(230)
left(90)
forward(10)
left(90)
forward(230)
end_fill()

# drawing first panel right open window

penup()
setposition(-72, 287)
fillcolor("darkgrey")
begin_fill()
pendown()
left(20)
forward(17)
right(20)
left(180)
forward(230)
left(90)
forward(7)
left(90)
forward(220)
end_fill()

penup()
setposition(-72, 287)
fillcolor("lightgrey")
begin_fill()
pendown()
left(20)
forward(17)
right(20)
left(90)
forward(10)
left(90)
forward(230)
left(90)
forward(10)
left(90)
forward(230)
end_fill()


# drawing details inside of window in first panel

def rectangles_inside_window():
     fillcolor("lightslategrey")
     begin_fill()
     pendown()
     left(63)
     forward(10)
     right(63)
     left(180)
     forward(200)
     left(90)
     forward(10)
     left(90)
     forward(195)
     end_fill()
     penup()

def panel_one_shading():
     left(110)
     pendown()
     color("slategrey")
     begin_fill()
     forward(10)
     right(20)
     left(90)
     forward(90)
     left(110)
     forward(10)
     right(110)
     left(180)
     forward(90)
     end_fill()

def outline_rectangle_first_panel():
     color("black")
     pendown()
     left(63)
     forward(10)
     right(63)
     left(180)
     forward(200)
     left(90)
     forward(10)
     left(90)
     forward(195)

     
pensize(1)
penup()
setposition(-295, 275)
rectangles_inside_window()

penup()
setposition(-295, 235)
pendown()
panel_one_shading()

pensize(1)
penup()
setposition(-295, 275)
pendown()
outline_rectangle_first_panel()

pensize(1)
penup()
setposition (-315, 275)
rectangles_inside_window()

penup()
setposition(-315, 235)
pendown()
panel_one_shading()

pensize(1)
penup()
setposition(-315, 275)
pendown()
outline_rectangle_first_panel()

# drawing small edge under the window first panel
pensize(2)
penup()
setposition(-64, 62)
fillcolor("lightgrey")
begin_fill()
pendown()
left(180)
right(65)
forward(20)
left(65)
right(90)
forward(215)
right(90)
forward(10)
right(90)
forward(235)
end_fill()

fillcolor("darkgrey")
begin_fill()
right(90)
forward(10)
right(65)
forward(20)
left(65)
right(90)
forward(217)
right(90)
forward(10)
right(90)
forward(217)
left(25)
forward(20)
end_fill()

left(180)
forward(20)
right(25)
left(90)
forward(10)

penup()
setposition(-90, 78)
right(90)
fillcolor("grey")
begin_fill()
pendown()
forward(200)
left(90)
forward(5)
left(90)
forward(200)
left(90)
forward(5)
end_fill()

pensize(3)
# first panel bear head
def make_head_shape():
     pendown()
     circle(45, 180)

     forward(10)
     for i in range(13):
          forward(1.15)
          left(4)

     for i in range(33):
          forward(1)
          left(1)
     penup()
     left(2)
     forward(20)
     pendown()

     for i in range(36):
          forward(1)
          left(1.5)
     left(30)
     for i in range(27):
          forward(1)
          left(0.3)

penup()
setposition(-145, 150)
fillcolor("peru")
begin_fill()
make_head_shape()
end_fill()


# draw first panel bear right ear
pensize(2)
penup()
setposition(-151, 160)
right(90)
begin_fill()
pendown()
left(16)
circle(15.5, 215)
end_fill()

fillcolor("peachpuff")
begin_fill()
penup()
right(23)
right(180)
setposition(-153, 170)
pendown()
circle(5.5, 180)
left(90)
forward(11)
end_fill()

# draw first panel bear left ear
def make_small_ear():
     for i in range(7):
          forward(2)
          left(20)
     for i in range(9):
          forward(2.7)
          left(15)
penup()
left(48)
setposition(-220, 180)
fillcolor("peru")
begin_fill()
pendown()
right(20)
left(90)
make_small_ear()
left(80)
forward(18)
end_fill()
penup()

# drawing the facial features of the first panel bear

# function to draw oval
def oval():
     left(45)
     for loop in range(2):
          circle(radius,90)
          circle(radius/2,90)
     right(45)
# set mouse to right position to draw right eye for first panel
left(32)
right(90)
setposition(-182, 143)

# call oval function to draw the right eye for first panel bear
radius=3
pendown()
color("black")
begin_fill()
oval()
end_fill()

#change setposition to draw left eye for first panel bear
penup()
setposition(-212, 143)

# call eye function to draw left eye for first panel bear
pendown()
begin_fill()
oval()
end_fill()

#setposition to under the eyes/ mouth area for first panel bear
penup()
setposition(-197, 131)
pendown()

#draw the mouth outline for first panel bear
radius = 11
color("burlywood")
begin_fill()
oval()
end_fill()

#set position to draw mouth of first panel bear

penup()
setposition(-200, 141)

#draw mouth of first panel bear
pensize(2)
color("black")
begin_fill()
pendown()
circle(3,360,3)
end_fill()
right(90)
forward(5)
left(45)
forward(4)
backward(4)
right(45)
right(45)
forward(4)
left(45)

#draw body for first panel bear
pensize(3)
penup()
setposition(-218, 118)
pendown()
fillcolor("peru")
begin_fill()
for i in range(16):
     forward(1.7)
     right(3.2)
right(25)
circle(10, 174)
pensize(1)
forward(68)
left(90)
pensize(2)
for i in range(6):
     forward(6.5)
     left(2)
end_fill()


# outline of first panel bears arms
pensize(3)
right(10)
left(180)
penup()
setposition(-213,118)
forward(43)
left(90)
pendown()
circle(10,180)

penup()
backward(29)
pendown()
forward(10)
circle(11, 190)
for i in range(17):
     forward(1.4)
     left(1.5)
pensize(2)
backward(7)
right(34)
fillcolor("grey")
begin_fill()
forward(20)
penup()
right(90)
forward(5)
right(90)
forward(20)
right(90)
forward(5)
end_fill()

#making paw details for first panel bear

penup()
right(93.5)
right(90)
setposition(-193, 81)
right(40)
pendown()
forward(5.5)
left(40)

penup()
setposition(-215, 81)
left(40)
pendown()
forward(5.5)
right(40)

# make second panel window frame
#call window frame functions and set to correct position

length = 240
pensize(2)
color("black")
penup()
setposition(150,180)
fillcolor("lightgrey")
begin_fill()
outerframe(length)
forward(150)
end_fill()
length= length-20
setposition(150, 180)
innerframe(length)

# draw left open window of second panel
fillcolor("grey")
begin_fill()
penup()
right(180)
right(30)
pendown()
forward(20)
left(30)
left(180)
forward(244)
left(180)
left(50)
forward(14.5)
right(50)
forward(217)
end_fill()

#make shadow for left open window of second panel
fillcolor("lightslategrey")
begin_fill()
penup()
backward(10)
left(90)
left(60)
forward(18)
pendown()
left(30)
forward(204)
left(90)
forward(15)
penup()
left(90)
forward(6)
left(49)
pendown()
forward(9)
right(49)
forward(204)
end_fill()

#return to original position before shadow
penup()
forward(20)
right(48)
forward(14.5)
left(48)
right(90)

# draw extension of left window of second panel
fillcolor("darkgrey")
begin_fill()
pendown()
forward(10)
right(90)
forward(242)
right(90)
forward(10)
right(90)
end_fill()
forward(242)
end_fill()

#setposition to draw right open window of second panel
penup()
right(90)
forward(10)
right(90)
forward(16)
left(90)
forward(200)

# draw right open window of second panel
fillcolor("grey")
begin_fill()
left(20)
pendown()
forward(44)
right(110) 
forward(244)
right(105)
forward(40)
left(15)
right(90)
forward(218)
end_fill()

fillcolor("darkgrey")
begin_fill()
penup()
right(69)
forward(40)
left(69)
right(90)
pendown()
forward(10)
right(90)
forward(244)
right(90)
forward(10)
right(90)
forward(244)
end_fill()


#draw small squares inside the right open window of second panel
penup()
setposition(290, 270)
left(105)
fillcolor("lightslategrey")
begin_fill()
pendown()
forward(23)
right(105)
left(180)
forward(74)
left(90)
forward(23)
left(90)
forward(79)
end_fill()

penup()
setposition(290, 180)
left(95)
fillcolor("lightslategrey")
begin_fill()
pendown()
forward(23)
right(95)
left(180)
forward(74)
left(90)
forward(23)
left(90)
forward(77)
end_fill()

# draw ledge on the inside of second panel window
# set position right above the bottom window frame of second panel
penup()
setposition(258,70)
pendown()

# draw ledge on second panel window
fillcolor("grey")
begin_fill()
for i in range(2):
     forward(5)
     left(90)
     forward(198)
     left(90)
end_fill()

# draw second panel bear head and body

#setposition to draw second panel bear head and body
penup()
setposition(163,170)

# draw second panel bear head
pendown()
pensize(3)
fillcolor("white")
begin_fill()
make_head_shape()
end_fill()

# set position to draw body of second panel bear
penup()
backward(38)
left(90)
forward(62)
left(90)
right(20)

# draw body of second panel bear
fillcolor("white")
begin_fill()
pendown()
for i in range(6):
     forward(2.2)
     right(1.8)
for i in range(11):
     forward(5)
     left(4.5)
left(72)
forward(63)
left(90)
right(20)
forward(13)
left(20)
circle(10,100)
right(180)
circle(10, 180)
forward(10)
for i in range(4):
     forward(2)
     right(15)
right(60)
forward(23)
end_fill()

# draw small dinosaur of second panel
penup()
left(25)
backward(24)
left(90)
backward(18)
right(90)
pendown()
fillcolor("lightgreen")
begin_fill()
circle(19,180)
left(90)
forward(34)
end_fill()

# draw dinosaur yellow scales
def make_scales():
     pensize(1)
     pendown()
     fillcolor("gold")
     begin_fill()
     circle(5,360,3)
     left(90)
     backward(7)
     right(125)
     end_fill()
left(90)
penup()
forward(18)
left(90)
forward(14)
right(90)
for i in range(4):
     make_scales()
penup()
left(30)
forward(3)
pendown()
fillcolor("gold")
begin_fill()
circle(5,360,3)
end_fill()

# draw dinosaur facial features
pensize(2)
penup()
backward(30)
left(7)
color("black")
pendown()
forward(3)
backward(3)
penup()
right(180)
backward(11)
pendown()
forward(3)

#draw dinosaur mouth of second panel
penup()
pensize(3)
setposition(124, 119)
fillcolor("pink")
begin_fill()
circle(4, 360,3)
end_fill()

# draw body shadow of second panel bear
pensize(1)
penup()
left(100)
forward(45)
right(90)
backward(16)
right(90)

pendown()
color("cornflowerblue")
begin_fill()
for i in range(2):
     forward(3)
     left(90)
     forward(50)
     left(90)
end_fill()

left(90)
forward(30)
begin_fill()
for i in range(8):
     forward(5)
     right(15)
forward(40)
left(90)
forward(4)
left(95)
for i in range(6):
     forward(2.2)
     right(1.8)
for i in range(11):
     forward(5)
     left(4.5)
end_fill()

penup()
right(20)
setposition(78,180)
pendown()
begin_fill()
for i in range(10):
     forward(5)
     left(7)
right(180)
left(10)
for i in range(9):
     forward(5)
     right(9.2)
end_fill()

# draw arm detail for bear of second panel
color("black")
pensize(3)
penup()
setposition(145, 95)
left(103)
pendown()
forward(30)

# tail for second panel bear
penup()
setposition(80, 90)
pendown()
fillcolor("cornflowerblue")
begin_fill()
circle(5)
end_fill()

# draw second panel bear left bear 
penup()
setposition(88, 205)
fillcolor("white")
begin_fill()
pendown()
right(40)
circle(15.5, 215)
end_fill()

pensize(1)
color("salmon")
fillcolor("pink")
begin_fill()
penup()
right(25)
right(180)
setposition(82, 197)
pendown()
circle(6, 180)
left(90)
forward(11)
end_fill()

# draw second panel bear right ear
color("black")
pensize(3)
penup()
setposition(153, 194)
fillcolor("white")
begin_fill()
pendown()
right(20)
left(90)
right(90)
right(90)
make_small_ear()
left(80)
forward(18)
end_fill()
penup()

# second panel bear eyes
radius = 4
penup()
setposition(115, 165)
left(50)
pendown()
fillcolor("black")
begin_fill()
oval()
end_fill()

right(5)
penup()
forward(28)
left(90)
forward(4)
right(70)
pendown()
fillcolor("black")
begin_fill()
oval()
end_fill()

# draw second panel bear nose and mouth
penup()
setposition(130, 159)
pensize(2)
right(8)
color("black")
begin_fill()
pendown()
circle(3,360,3)
end_fill()
right(90)
forward(7)
right(90)
forward(6)
backward(9)

#draw second panel bear pink cheeks
penup()
setposition(104, 161)
def make_pink_cheeks():
     pendown()
     color("lightpink")
     begin_fill()
     circle(6)
     end_fill()
make_pink_cheeks()
penup()
setposition(147, 161)
make_pink_cheeks()

# third panel window frame
penup()
right(7.5)
color("black")
setposition(-190, -180)

length = 235
pensize(2)
color("black")
penup()
fillcolor("dimgrey")
begin_fill()
outerframe(length)
forward(150)
end_fill()
length= length-20
setposition(-190, -180)
innerframe(length)
# third panel sky colour
fillcolor("cornflowerblue")
begin_fill()
penup()
for i in range(2):
     forward(215)
     left(90)
     forward(117.5)
     left(90)
end_fill()
right(90)
backward(117.5)
left(90)
fillcolor("lightsteelblue")
begin_fill()
penup()
for i in range(2):
     forward(215)
     left(90)
     forward(10)
     left(90)
end_fill()
right(90)
backward(10)
left(90)
fillcolor("seashell")
begin_fill()
penup()
for i in range(2):
     forward(215)
     left(90)
     forward(27.5)
     left(90)
end_fill()
right(90)
backward(27.5)
left(90)
fillcolor("mistyrose")
begin_fill()
penup()
for i in range(2):
     forward(215)
     left(90)
     forward(60)
     left(90)
end_fill()

# draw right open window of third panel window
pendown()
left(90)
forward(60)
right(90)
fillcolor("grey")
begin_fill()
for i in range(2):
     forward(10)
     right(90)
     forward(215)
     right(90)
end_fill()

# draw left open window of third panel window
penup()
forward(215)
right(180)
pendown()
fillcolor("grey")
begin_fill()
for i in range(2):
     forward(10)
     left(90)
     forward(215)
     left(90)
end_fill()

begin_fill()
forward(12)
left(15)
forward(32)
right(15)
left(90)
forward(195)
left(67)
forward(35)
right(67)
left(180)
forward(215)
end_fill()

penup()
backward(200)
def third_panel_window_detail():
     fillcolor("lightgrey")
     begin_fill()
     left(60)
     forward(6)
     pendown()
     forward(10)
     right(60)
     forward(170)
     right(90)
     forward(10)
     right(90)
     forward(176)
     end_fill()
def third_panel_window_detail_shading():
     fillcolor("grey")
     begin_fill()
     backward(60)
     penup()
     right(60)
     forward(12)
     left(60)
     pendown()
     left(180)
     forward(50)
     right(90)
     penup()
     forward(10)
     pendown()
     right(90)
     forward(48)
     end_fill()

third_panel_window_detail()
third_panel_window_detail_shading()
penup()
forward(57)
right(90)
forward(9)
left(90)
right(180)
third_panel_window_detail()
third_panel_window_detail_shading()

# draw crescent moon
radiusone=35
radiustwo=30
def firstmoon():
     pendown()
     color("white")
     begin_fill()
     circle(radiusone)
     end_fill()
def secondmoon():
     color("cornflowerblue")
     begin_fill()
     circle(radiustwo)
     end_fill()
penup()
setposition(-120, -130)
firstmoon()
setposition(-110, -120)
secondmoon()
# draw third panel bear head
penup()
setposition(-170, -205)
pendown()
color("black")
fillcolor("grey")
begin_fill()
make_head_shape()
end_fill()

penup()
setposition(-170, -208)
pensize(3)
color("peru")
pendown()
circle(45, 130)

# draw third panel bear right ear
pensize(2)
penup()
setposition(-180, -196)
right(180)
right(40)
color("black")
fillcolor("grey")
begin_fill()
pendown()
left(16)
circle(15.5, 215)
end_fill()

# draw third panel bear left ear
penup()
left(85)
setposition(-245, -176)
fillcolor("grey")
begin_fill()
pendown()
left(90)
make_small_ear()
left(80)
penup()
forward(18)
end_fill()
penup()

# draw third panel bear body
left(47)
setposition(-227, -240)
left(180)

pendown()
color("black")
fillcolor("grey")
begin_fill()
right(35)
for i in range(21):
     forward(3)
     left(1.5)
for i in range(10):
     forward(4)
     left(10)
forward(5)
right(98)
forward(16)
left(90)
forward(17)
left(90)
forward(18)
right(90)
left(15)
for i in range(37):
     forward(1.5)
     left(2.8)
# draw third panel bear arm
forward(10)
penup()
right(5)
forward(33)
end_fill()
backward(49)
right(23)
right(90)
pendown()
begin_fill()
circle(10, 130)
forward(39)
left(5)
penup()
left(90)
forward(10)
end_fill()

forward(8)
left(90)
forward(26)
color("black")
pendown()
forward(18)

penup()
color("peru")
circle(6, 178)
pendown()
forward(46)

#draw left leg of third panel bear
penup()
left(50.5)
setposition(-224, -324)
left(90)
color("black")
fillcolor("dimgrey")
begin_fill()
pendown()
forward(17)
right(90)
forward(17)
right(90)
forward(18)
end_fill()

# draw tail of third panel bear
penup()
setposition(-227, -295)
left(90)
pendown()
circle(6,180)

# draw fourth panel window frame
penup()
setposition(160, -180)
length = 245
pensize(2)
color("black")
penup()
fillcolor("dimgrey")
begin_fill()
outerframe(length)
forward(150)
end_fill()
length= length-20
setposition(160,-180)
innerframe(length)

left(90)
forward(225)
right(90)
forward(225)
left(180)

fillcolor("cornflowerblue")
begin_fill()
penup()
for i in range(2):
     forward(225)
     left(90)
     forward(123)
     left(90)
end_fill()
right(90)
backward(123)
left(90)
fillcolor("lightsteelblue")
begin_fill()
penup()
for i in range(2):
     forward(225)
     left(90)
     forward(14)
     left(90)
end_fill()
right(90)
backward(14)
left(90)
fillcolor("seashell")
begin_fill()
penup()
for i in range(2):
     forward(225)
     left(90)
     forward(28)
     left(90)
end_fill()
right(90)
backward(28)
left(90)
fillcolor("mistyrose")
begin_fill()
penup()
for i in range(2):
     forward(225)
     left(90)
     forward(60)
     left(90)
end_fill()

# draw fourth panel right window
fillcolor("dimgrey")
begin_fill()
penup()
left(90)
forward(60)
right(90)
pendown()
right(35)
forward(7)
left(35)
right(90)
forward(216)
right(35)
forward(8)
left(215)
forward(225)
end_fill()

right(125)
forward(7)
left(35)
begin_fill()
forward(218)
left(90)
forward(5)
left(90)
forward(221)
left(90)
end_fill()

penup()
forward(6)
left(90)
forward(2)
pendown()
begin_fill()
for i in range(2):
     forward(10)
     right(90)
     forward(214)
     right(90)
end_fill()

right(90)
penup()
pendown()
begin_fill()
forward(214)
left(90)
forward(219)
right(90)
forward(6)
right(90)
forward(221)
right(90)
forward(6)
end_fill()

begin_fill()
penup()
right(90)
forward(11)
pendown()
left(35)
forward(30)
right(35)
left(90)
forward(180)
left(56)
forward(29)
right(236)
forward(215)
end_fill()

# draw fourth panel right open window details on the inside
penup()
backward(20)
left(90)
forward(8)
pendown()
pensize(2)
fillcolor("white")
begin_fill()
for i in range(2):
     forward(8)
     left(90)
     forward(180)
     left(90)
end_fill()

# revert back to original position
penup()
backward(8)
right(90)
forward(17)
# draw fourth panel left open window
left(90)
forward(210)
left(90)
pendown()
fillcolor("dimgrey")
begin_fill()
for i in range(2):
     forward(214)
     left(90)
     forward(8)
     left(90)
end_fill()

begin_fill()
penup()
left(90)
forward(8)
pendown()
right(25)
forward(17)
left(25)
right(90)
forward(193)
right(49)
forward(21)
left(229)
forward(214)
end_fill()

#draw detailing inside of fourth panel left window
penup()
backward(214)
right(90)
forward(9)
left(90)
forward(20)
pensize(4)
pendown()
forward(80)
penup()
forward(14)
pendown()
forward(80)
right(90)

#draw crescent moon
radiusone=30
radiustwo=25
penup()
setposition(125, -150)
firstmoon()
setposition(140, -138)
secondmoon()

#draw fourth panel bear head
penup()
setposition(258, -190)
pendown()
pensize(3)
color("black")
fillcolor("grey")
begin_fill()
left(90)
make_head_shape()
end_fill()

# make fourth panel bear right ear
pensize(2)
penup()
setposition(252, -170)
left(180)
left(50)
pendown()
begin_fill()
make_small_ear()
left(75)
forward(17)
end_fill()

# draw streak of white on fourth panel bear head
right(125)
penup()
right(92)
setposition(258, -191)
pendown()
color("white")
pensize(1.8)
circle(45, 180)
forward(10)
penup()
left(180)
setposition(257, -191)
pensize(2.5)
pendown()
color("grey")
circle(45, 65)

# draw fourth panel bear left ear
pensize(2)
penup()
right(38)
color("black")
fillcolor("grey")
setposition(195, -160)
begin_fill()
pendown()
circle(15.5, 215)
end_fill()

penup()
left(38)
setposition(194, -160)
right(63)
left(180)
pendown()
color("white")
circle(14.8, 210)

# draw fourth panel bear body
penup()
setposition(229, -227)
pendown()
color("black")
right(65)
left(17)

fillcolor("grey")
begin_fill()
pendown()
for i in range(6):
     forward(2.4)
     left(1.8)
for i in range(11):
     forward(4.7)
     right(4.5)
right(72)
forward(26)
left(82)
forward(15)
right(90)
forward(18)
right(90)
forward(15)
right(82)
right(180)
right(23)
forward(14)
left(23)
right(90)
forward(15)
left(124)
for i in range(17):
     forward(1.8)
     right(10)
right(13)
for i in range(14):
     forward(3)
     left(1.8)
end_fill()

# fourth panel bear front leg
penup()
left(147)
setposition(185, -268)
pendown()
backward(15)
forward(15)
right(22)
begin_fill()
left(10)
forward(15)
right(10)
left(90)
forward(15)
left(90)
forward(26)
left(150)
forward(11)
right(150)
left(90)
forward(11)
end_fill()

pensize(3)
backward(2)
left(105)
color("white")
penup()
forward(3)
pendown()
forward(10)

#revert to original position
right(16)
color("black")

# draw fourth panel green dinosaur body
penup()
pensize(2)
setposition(191, -223)
left(10)
pendown()
fillcolor("lightgreen")
begin_fill()
for i in range(10):
     forward(3.3)
     left(12)
left(90)
forward(29.5)
end_fill()

# draw fourth panel dinosaur scales
pensize(1)
penup()
right(160)
right(140)
setposition(187,-222)
pendown()
fillcolor("gold")
begin_fill()
circle(5, 360, 3)
end_fill()

move = 6
for i in range(2):
     penup()
     left(90)
     forward(9)
     right(90)
     backward(move)
     left(30)
     begin_fill()
     pendown()
     circle(5, 360, 3)
     end_fill()
     move = move + 1.2

# draw tail of fourth panel bear
pensize(2)
penup()
left(25)
left(180)
right(25)
setposition(241.5, -280)
pendown()
fillcolor("grey")
begin_fill()
circle(8, 210)
end_fill()

# draw third panel trail of white dots
def create_white_dot():
     pendown()
     color("white")
     begin_fill()
     circle(radius)
     end_fill()
     penup()
# set position to draw white trails
penup()
setposition(-360, -160)
radius = 1
create_white_dot()
setposition(-335, -145)
radius = 1.3
create_white_dot()
setposition(-310, -185)
radius = 1.5
create_white_dot()
setposition(-285, -195)
radius = 0.5
create_white_dot()
setposition(-275, -199)
radius = 0.5
create_white_dot()
setposition(-145, -190)
radius = 1
create_white_dot()
setposition(-90, -199)
radius = 0.5
create_white_dot()
setposition(-68, -173)
radius = 1
create_white_dot()
setposition(-55, -170)
radius = 0.4
create_white_dot()
setposition(-51, -182)
radius = 0.4
create_white_dot()
setposition(-30, -155)
radius = 1.3
create_white_dot()

# draw fourth panel trail of white dots
setposition(2, -165)
radius = 0.3
create_white_dot()
setposition(6, -145)
radius = 0.5
create_white_dot()
setposition(10, -125)
radius = 0.4
create_white_dot()
setposition(23, -180)
radius = 0.5
create_white_dot()
setposition(31, -135)
radius = 1.4
create_white_dot()
setposition(45, -162)
radius = 0.3
create_white_dot()
setposition(90, -182)
radius = 0.3
create_white_dot()
setposition(125, -173)
radius = 0.3
create_white_dot()
setposition(289, -184)
radius = 0.8
create_white_dot()
setposition(300, -168)
radius = 0.5
create_white_dot()
setposition(319, -177)
radius = 0.4
create_white_dot()

# adding small details that I missed
#third panel ear shadow
pensize(2)
penup()
setposition(-178, -196)
right(180)
color("peru")
pendown()
left(16)
circle(14.3, 190)
# fourth panel foot line
penup()
right(16)
right(120)
setposition(202, -303)
pensize(2)
color("black")
pendown()
forward(5)

# write words on third and fourth panel
color("white")
penup()
right(90)
setposition(-260, -50)
write("DO YOU SEE...", font=("Comic Sans Ms", 15, "normal"))
penup()
setposition(98, -50)
write("...WHAT I SEE?", font=("Comic Sans Ms", 15, "normal"))

# fourth panel extra stars
def colored_star():
  size = 4.5
  color("yellow")
  width(4)
  angle = 120
  fillcolor("yellow")
  begin_fill()
  pendown()
  for side in range(5):
    forward(size)
    right(angle)
    forward(size)
    right(72 - angle)
  end_fill()
  penup()

penup()
setposition(170, -100)
colored_star()
right(30)
setposition(104, -163)
colored_star()
left(45)
setposition(213, -128)
colored_star()

# third panel extra stars
penup()
setposition(-127, -100)
colored_star()
right(20)
setposition(-104, -152)
colored_star()
left(45)
setposition(-233, -133)
colored_star()

# move the mouse out of the frame
penup()
color("midnightblue")
left(90)
forward(100)
